spring:
  application:
    name: crm-cqrs
  datasource:
    url: "jdbc:postgresql://localhost:5432/e-commerce"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8080
